TRAIN:
  BATCHSIZE: 64
#TEST:
#  CHECKPOINT: './base_2/checkpoints/resnet50_60.pth'
#INPUT:
#  RANDOM_ERASING: False
#OPTIM:
#  LR: 'warmup'
#  WARMUP_ITERS: 20
#RERANK:
#  ENABLE: True
#LOSS:
#  SMOOTH: True
#EVAL:
#  DIST: 'cos'
